In [1]:
import pandas as pd
import numpy as np

import pickle

from sklearn.feature_extraction.text import TfidfVectorizer 

from sklearn.svm import SVC 

import warnings
warnings.filterwarnings("ignore")

In [2]:
data_train = pd.read_csv('data_train_nostemming_nostopword.csv', sep=';')
data_test = pd.read_csv('data_test_nostemming_nostopword.csv', sep=';')

In [3]:
data_train.head()

review_text  price  packaging  \
0  dair dulu penasaran banget sama skincare ini k...     -1          0   
1  dari awal ngincer ini karena banyak yang bilan...      0          0   
2  aku suka sekali tabirsurya ini teksturnya ring...      0          1   
3  pernah nyobain ini pas muka lagi stress ny dan...      0          0   
4  paling suka sama gokujyun losion untuk merek h...      1          0   

   product  aroma  
0      0.0      0  
1      1.0      0  
2      1.0      0  
3     -1.0      0  
4      1.0      0

In [4]:
data_test.head()

review_text  price  packaging  \
0  produk favorit banget enak dipake plus tidak p...     -1          0   
1  awalnya agak lengket pas baru dipake tapi untu...      1          0   
2  minyak kontrol lumayan bisa ngempesin jerawat ...      1          0   
3  favorite banget selain harganya terjangkau ban...      1          0   
4  ini adalah exfoliant toner yang saya pakai seb...      0          0   

   product  aroma  
0      1.0      0  
1      0.0      0  
2     -1.0      0  
3      1.0      0  
4      1.0      0

In [5]:
data_train.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [6]:
data_test.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [7]:
X_train = data_train['review_text']
X_test = data_test['review_text']

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
fitur_train = TfidfVectorizer().fit(X_train)
tfidf_train = fitur_train.transform(X_train).toarray()
tfidf_test = fitur_train.transform(X_test).toarray()

In [9]:
def get_fitur_tfidf(tfidf, fitur):
    terms = tfidf.get_feature_names()
    sums = fitur.sum(axis = 0)

    data = []
    for col, term in enumerate(terms):
        data.append((term, sums[col] ))
    ranking = pd.DataFrame(data, columns=['Terms','TF-IDF'])
    return ranking

In [10]:
out_tfidf_tr = get_fitur_tfidf(fitur_train, tfidf_train)

In [11]:
out_tfidf_tr.shape

(11291, 2)

In [12]:
#FEATURE SELECTION CHI SQUARE
from sklearn import datasets
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [13]:
x_chi_tr = tfidf_train
x_chi_test = tfidf_test

In [14]:
#y_chi_tr = np.array(data_train[['price','packaging','aroma','product']])
#y_chi_test = np.array(data_test[['price','packaging','aroma','product']])

In [15]:
y_price_tr = (data_train['price'])
y_packaging_tr = (data_train['packaging'])
y_product_tr = (data_train['product'])
y_aroma_tr = (data_train['aroma'])

In [16]:
y_price_test = (data_test['price'])
y_packaging_test = (data_test['packaging'])
y_product_test = (data_test['product'])
y_aroma_test = (data_test['aroma'])

In [17]:
chi_price_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_aroma_tr)


chi_price_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_price_test)
chi_packaging_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_packaging_test)
chi_product_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_product_test)
chi_aroma_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_aroma_test)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

#aspek price
knn_price_7 = KNeighborsClassifier(n_neighbors=50)


knn_price_7.fit(chi_price_tr, y_price_tr)


predictions_price_7 = knn_price_7.predict(chi_price_test)

#aspek packaging

knn_packaging_7 = KNeighborsClassifier(n_neighbors=50)

knn_packaging_7.fit(chi_packaging_tr, y_packaging_tr)

predictions_packaging_7 = knn_packaging_7.predict(chi_packaging_test)

#aspek product

knn_product_7 = KNeighborsClassifier(n_neighbors=50)



knn_product_7.fit(chi_product_tr, y_product_tr)



predictions_product_7 = knn_product_7.predict(chi_product_test)

#aspek aroma

knn_aroma_7 = KNeighborsClassifier(n_neighbors=50)


knn_aroma_7.fit(chi_aroma_tr, y_aroma_tr)


predictions_aroma_7 = knn_aroma_7.predict(chi_aroma_test)


In [19]:
#Nilai price

knn7_price_skor=knn_price_7.score(chi_price_test,y_price_test)

#nilai packaging

knn7_packaging_skor=knn_packaging_7.score(chi_packaging_test,y_packaging_test)

#nilai product

knn7_product_skor=knn_product_7.score(chi_product_test,y_product_test)

#nilai aroma

knn7_aroma_skor=knn_aroma_7.score(chi_aroma_test,y_aroma_test)

print('=============== PRICE ===================')

print('Nilai Model price K-NN pada K-50           :',knn7_price_skor * 100 ,'%')

print('                                                                             ')
print('============= PACKAGING ================')

print('Nilai Model packaging K-NN pada K-50       :',knn7_packaging_skor * 100 ,'%')

print('                                                                             ')
print('============= PRODUCT ================')

print('Nilai Model product K-NN pada K-50         :',knn7_product_skor * 100 ,'%')

print('                                                                             ')
print('============= AROMA ================')

print('Nilai Model aroma K-NN pada K-50           :',knn7_aroma_skor * 100 ,'%')


=============== PRICE ===================
Nilai Model price K-NN pada K-50           : 52.65151515151515 %
                                                                             
============= PACKAGING ================
Nilai Model packaging K-NN pada K-50       : 83.96464646464646 %
                                                                             
============= PRODUCT ================
Nilai Model product K-NN pada K-50         : 67.8030303030303 %
                                                                             
============= AROMA ================
Nilai Model aroma K-NN pada K-50           : 80.55555555555556 %


In [20]:
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
#from sklearn.metrics import  multilabel_confusion_matrix

In [21]:
#Evaluasi aspek Price Pada K = 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  3 139  10]
 [  0 404  15]
 [  0 211  10]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.61
Macro Recall: 0.34
Macro F1-score: 0.27

Weighted Precision: 0.56
Weighted Recall: 0.53
Weighted F1-score: 0.39

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.02      0.04       152
           0       0.54      0.96      0.69       419
           1       0.29      0.05      0.08       221

    accuracy                           0.53       792
   macro avg       0.61      0.34      0.27       792
weighted avg       0.56      0.53      0.39       792



In [22]:
#Evaluasi aspek Packaging pada K= 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  35   6]
 [  0 665   7]
 [  0  79   0]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.28
Macro Recall: 0.33
Macro F1-score: 0.31

Weighted Precision: 0.72
Weighted Recall: 0.84
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      0.99      0.92       672
           1       0.00      0.00      0.00        79

    accuracy                           0.84       792
   macro avg       0.28      0.33      0.31       792
weighted avg       0.72      0.84      0.78       792



In [23]:
#Evaluasi aspek Product pada K= 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  3   0 132]
 [  4   0 117]
 [  2   0 534]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.34
Macro Recall: 0.34
Macro F1-score: 0.28

Weighted Precision: 0.52
Weighted Recall: 0.68
Weighted F1-score: 0.56

Classification Report

              precision    recall  f1-score   support

          -1       0.33      0.02      0.04       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.34      0.34      0.28       792
weighted avg       0.52      0.68      0.56       792



In [24]:
#Evaluasi aspek Aroma Pada K=50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  36   4]
 [  0 607   8]
 [  0 106  31]]

Accuracy: 0.81

Micro Precision: 0.81
Micro Recall: 0.81
Micro F1-score: 0.81

Macro Precision: 0.51
Macro Recall: 0.40
Macro F1-score: 0.41

Weighted Precision: 0.75
Weighted Recall: 0.81
Weighted F1-score: 0.75

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.81      0.99      0.89       615
           1       0.72      0.23      0.34       137

    accuracy                           0.81       792
   macro avg       0.51      0.40      0.41       792
weighted avg       0.75      0.81      0.75       792

