In [1]:
import pandas as pd
import numpy as np

import pickle

from sklearn.feature_extraction.text import TfidfVectorizer 

from sklearn.svm import SVC 

import warnings
warnings.filterwarnings("ignore")

In [2]:
data_train = pd.read_csv('data_train_lengkap.csv', sep=';')
data_test = pd.read_csv('data_test_lengkap.csv', sep=';')

In [3]:
data_train.head()

review_text  price  packaging  \
0  dair penasaran banget skincare reviewnya banya...     -1          0   
1  ngincer bilang dupenya ski baca review tertawa...      0          0   
2  suka tabirsurya tekstur ringan serap banget ku...      0          1   
3  nyobain pas muka lagi stress ny desperate bang...      0          0   
4  suka gokujyun losion merek hada labo lotionnya...      1          0   

   product  aroma  
0      0.0      0  
1      1.0      0  
2      1.0      0  
3     -1.0      0  
4      1.0      0

In [4]:
data_test.head()

review_text  price  packaging  \
0  produk favorit banget enak dipake plus tidak r...     -1          0   
1  lengket pas dipake hitungan tabirsurya yang ti...      1          0   
2  minyak kontrol lumayan ngempesin jerawat efek ...      1          0   
3  favorite banget harga terjangkau banget gak ha...      1          0   
4  exfoliant toner pakai bagi step double toning ...      0          0   

   product  aroma  
0      1.0      0  
1      0.0      0  
2     -1.0      0  
3      1.0      0  
4      1.0      0

In [5]:
data_train.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [6]:
data_test.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [7]:
X_train = data_train['review_text']
X_test = data_test['review_text']

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
fitur_train = TfidfVectorizer().fit(X_train)
tfidf_train = fitur_train.transform(X_train).toarray()
tfidf_test = fitur_train.transform(X_test).toarray()

In [9]:
def get_fitur_tfidf(tfidf, fitur):
    terms = tfidf.get_feature_names()
    sums = fitur.sum(axis = 0)

    data = []
    for col, term in enumerate(terms):
        data.append((term, sums[col] ))
    ranking = pd.DataFrame(data, columns=['Terms','TF-IDF'])
    return ranking

In [10]:
out_tfidf_tr = get_fitur_tfidf(fitur_train, tfidf_train)

In [11]:
out_tfidf_tr.shape

(7361, 2)

In [12]:
#FEATURE SELECTION CHI SQUARE
from sklearn import datasets
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [13]:
x_chi_tr = tfidf_train
x_chi_test = tfidf_test

In [14]:
#y_chi_tr = np.array(data_train[['price','packaging','aroma','product']])
#y_chi_test = np.array(data_test[['price','packaging','aroma','product']])

In [15]:
y_price_tr = (data_train['price'])
y_packaging_tr = (data_train['packaging'])
y_product_tr = (data_train['product'])
y_aroma_tr = (data_train['aroma'])

In [16]:
y_price_test = (data_test['price'])
y_packaging_test = (data_test['packaging'])
y_product_test = (data_test['product'])
y_aroma_test = (data_test['aroma'])

In [46]:
chi_price_tr_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_tr, y_aroma_tr)

chi_price_tr_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_tr, y_aroma_tr)

In [48]:
chi_price_test_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_test, y_price_test)
chi_packaging_test_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_test, y_packaging_test)
chi_product_test_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_test, y_product_test)
chi_aroma_test_all = SelectKBest(score_func=chi2, k='all').fit_transform(x_chi_test, y_aroma_test)

chi_price_test_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_5633 = SelectKBest(score_func=chi2, k=5521).fit_transform(x_chi_test, y_aroma_test)

chi_price_test_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_3755 = SelectKBest(score_func=chi2, k=3680).fit_transform(x_chi_test, y_aroma_test)

chi_price_test_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_2253 = SelectKBest(score_func=chi2, k=2208).fit_transform(x_chi_test, y_aroma_test)

chi_price_test_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_376 = SelectKBest(score_func=chi2, k=368).fit_transform(x_chi_test, y_aroma_test)

chi_price_test_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_76 = SelectKBest(score_func=chi2, k=74).fit_transform(x_chi_test, y_aroma_test)

chi_price_test_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_test, y_price_test)
chi_packaging_test_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_test, y_packaging_test)
chi_product_test_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_test, y_product_test)
chi_aroma_test_30 = SelectKBest(score_func=chi2, k=30).fit_transform(x_chi_test, y_aroma_test)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

#aspek price
knn_price_all = KNeighborsClassifier(n_neighbors=50)
knn_price_5633 = KNeighborsClassifier(n_neighbors=50)
knn_price_3755 = KNeighborsClassifier(n_neighbors=50)
knn_price_2253 = KNeighborsClassifier(n_neighbors=50)
knn_price_376 = KNeighborsClassifier(n_neighbors=50)
knn_price_76 = KNeighborsClassifier(n_neighbors=50)
knn_price_30 = KNeighborsClassifier(n_neighbors=50)

knn_price_all.fit(chi_price_tr_all, y_price_tr)
knn_price_5633.fit(chi_price_tr_5633, y_price_tr)
knn_price_3755.fit(chi_price_tr_3755, y_price_tr)
knn_price_2253.fit(chi_price_tr_2253, y_price_tr)
knn_price_376.fit(chi_price_tr_376, y_price_tr)
knn_price_76.fit(chi_price_tr_76, y_price_tr)
knn_price_30.fit(chi_price_tr_30, y_price_tr)

predictions_price_all = knn_price_all.predict(chi_price_test_all)
predictions_price_5633 = knn_price_5633.predict(chi_price_test_5633)
predictions_price_3755 = knn_price_3755.predict(chi_price_test_3755)
predictions_price_2253 = knn_price_2253.predict(chi_price_test_2253)
predictions_price_376 = knn_price_376.predict(chi_price_test_376)
predictions_price_76 = knn_price_76.predict(chi_price_test_76)
predictions_price_30 = knn_price_30.predict(chi_price_test_30)

#aspek packaging
knn_packaging_all = KNeighborsClassifier(n_neighbors=50)
knn_packaging_5633 = KNeighborsClassifier(n_neighbors=50)
knn_packaging_3755 = KNeighborsClassifier(n_neighbors=50)
knn_packaging_2253 = KNeighborsClassifier(n_neighbors=50)
knn_packaging_376 = KNeighborsClassifier(n_neighbors=50)
knn_packaging_76 = KNeighborsClassifier(n_neighbors=50)
knn_packaging_30 = KNeighborsClassifier(n_neighbors=50)

knn_packaging_all.fit(chi_packaging_tr_all, y_packaging_tr)
knn_packaging_5633.fit(chi_packaging_tr_5633, y_packaging_tr)
knn_packaging_3755.fit(chi_packaging_tr_3755, y_packaging_tr)
knn_packaging_2253.fit(chi_packaging_tr_2253, y_packaging_tr)
knn_packaging_376.fit(chi_packaging_tr_376, y_packaging_tr)
knn_packaging_76.fit(chi_packaging_tr_76, y_packaging_tr)
knn_packaging_30.fit(chi_packaging_tr_30, y_packaging_tr)

predictions_packaging_all = knn_packaging_all.predict(chi_packaging_test_all)
predictions_packaging_5633 = knn_packaging_5633.predict(chi_packaging_test_5633)
predictions_packaging_3755 = knn_packaging_3755.predict(chi_packaging_test_3755)
predictions_packaging_2253 = knn_packaging_2253.predict(chi_packaging_test_2253)
predictions_packaging_376 = knn_packaging_376.predict(chi_packaging_test_376)
predictions_packaging_76 = knn_packaging_76.predict(chi_packaging_test_76)
predictions_packaging_30 = knn_packaging_30.predict(chi_packaging_test_30)

#aspek product
knn_product_all = KNeighborsClassifier(n_neighbors=50)
knn_product_5633 = KNeighborsClassifier(n_neighbors=50)
knn_product_3755 = KNeighborsClassifier(n_neighbors=50)
knn_product_2253 = KNeighborsClassifier(n_neighbors=50)
knn_product_376 = KNeighborsClassifier(n_neighbors=50)
knn_product_76 = KNeighborsClassifier(n_neighbors=50)
knn_product_30 = KNeighborsClassifier(n_neighbors=50)

knn_product_all.fit(chi_product_tr_all, y_product_tr)
knn_product_5633.fit(chi_product_tr_5633, y_product_tr)
knn_product_3755.fit(chi_product_tr_3755, y_product_tr)
knn_product_2253.fit(chi_product_tr_2253, y_product_tr)
knn_product_376.fit(chi_product_tr_376, y_product_tr)
knn_product_76.fit(chi_product_tr_76, y_product_tr)
knn_product_30.fit(chi_product_tr_30, y_product_tr)

predictions_product_all = knn_product_all.predict(chi_product_test_all)
predictions_product_5633 = knn_product_5633.predict(chi_product_test_5633)
predictions_product_3755 = knn_product_3755.predict(chi_product_test_3755)
predictions_product_2253 = knn_product_2253.predict(chi_product_test_2253)
predictions_product_376 = knn_product_376.predict(chi_product_test_376)
predictions_product_76 = knn_product_76.predict(chi_product_test_76)
predictions_product_30 = knn_product_30.predict(chi_product_test_30)

#aspek aroma
knn_aroma_all = KNeighborsClassifier(n_neighbors=50)
knn_aroma_5633 = KNeighborsClassifier(n_neighbors=50)
knn_aroma_3755 = KNeighborsClassifier(n_neighbors=50)
knn_aroma_2253 = KNeighborsClassifier(n_neighbors=50)
knn_aroma_376 = KNeighborsClassifier(n_neighbors=50)
knn_aroma_76 = KNeighborsClassifier(n_neighbors=50)
knn_aroma_30 = KNeighborsClassifier(n_neighbors=50)

knn_aroma_all.fit(chi_aroma_tr_all, y_aroma_tr)
knn_aroma_5633.fit(chi_aroma_tr_5633, y_aroma_tr)
knn_aroma_3755.fit(chi_aroma_tr_3755, y_aroma_tr)
knn_aroma_2253.fit(chi_aroma_tr_2253, y_aroma_tr)
knn_aroma_376.fit(chi_aroma_tr_376, y_aroma_tr)
knn_aroma_76.fit(chi_aroma_tr_76, y_aroma_tr)
knn_aroma_30.fit(chi_aroma_tr_30, y_aroma_tr)

predictions_aroma_all = knn_aroma_all.predict(chi_aroma_test_all)
predictions_aroma_5633 = knn_aroma_5633.predict(chi_aroma_test_5633)
predictions_aroma_3755 = knn_aroma_3755.predict(chi_aroma_test_3755)
predictions_aroma_2253 = knn_aroma_2253.predict(chi_aroma_test_2253)
predictions_aroma_376 = knn_aroma_376.predict(chi_aroma_test_376)
predictions_aroma_76 = knn_aroma_76.predict(chi_aroma_test_76)
predictions_aroma_30 = knn_aroma_30.predict(chi_aroma_test_30)

In [50]:
#Nilai price
knn_all_price_skor=knn_price_all.score(chi_price_test_all,y_price_test)
knn_5633_price_skor=knn_price_5633.score(chi_price_test_5633,y_price_test)
knn_3755_price_skor=knn_price_3755.score(chi_price_test_3755,y_price_test)
knn_2253_price_skor=knn_price_2253.score(chi_price_test_2253,y_price_test)
knn_376_price_skor=knn_price_376.score(chi_price_test_376,y_price_test)
knn_76_price_skor=knn_price_76.score(chi_price_test_76,y_price_test)
knn_30_price_skor=knn_price_30.score(chi_price_test_30,y_price_test)
#nilai packaging

knn_all_packaging_skor=knn_packaging_all.score(chi_packaging_test_all,y_packaging_test)
knn_5633_packaging_skor=knn_packaging_5633.score(chi_packaging_test_5633,y_packaging_test)
knn_3755_packaging_skor=knn_packaging_3755.score(chi_packaging_test_3755,y_packaging_test)
knn_2253_packaging_skor=knn_packaging_2253.score(chi_packaging_test_2253,y_packaging_test)
knn_376_packaging_skor=knn_packaging_376.score(chi_packaging_test_376,y_packaging_test)
knn_76_packaging_skor=knn_packaging_76.score(chi_packaging_test_76,y_packaging_test)
knn_30_packaging_skor=knn_packaging_30.score(chi_packaging_test_30,y_packaging_test)
#nilai product

knn_all_product_skor=knn_product_all.score(chi_product_test_all,y_product_test)
knn_5633_product_skor=knn_product_5633.score(chi_product_test_5633,y_product_test)
knn_3755_product_skor=knn_product_3755.score(chi_product_test_3755,y_product_test)
knn_2253_product_skor=knn_product_2253.score(chi_product_test_2253,y_product_test)
knn_376_product_skor=knn_product_376.score(chi_product_test_376,y_product_test)
knn_76_product_skor=knn_product_76.score(chi_product_test_76,y_product_test)
knn_30_product_skor=knn_product_30.score(chi_product_test_30,y_product_test)
#nilai aroma

knn_all_aroma_skor=knn_aroma_all.score(chi_aroma_test_all,y_aroma_test)
knn_5633_aroma_skor=knn_aroma_5633.score(chi_aroma_test_5633,y_aroma_test)
knn_3755_aroma_skor=knn_aroma_3755.score(chi_aroma_test_3755,y_aroma_test)
knn_2253_aroma_skor=knn_aroma_2253.score(chi_aroma_test_2253,y_aroma_test)
knn_376_aroma_skor=knn_aroma_376.score(chi_aroma_test_376,y_aroma_test)
knn_76_aroma_skor=knn_aroma_76.score(chi_aroma_test_76,y_aroma_test)
knn_30_aroma_skor=knn_aroma_30.score(chi_aroma_test_30,y_aroma_test)

print('=============== PRICE ===================')
print('Nilai Model price K-NN pada K-50 tanpa seleksi                      :',knn_all_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 5633         :',knn_5633_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 3755         :',knn_3755_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 2253         :',knn_2253_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 376          :',knn_376_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 76           :',knn_76_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50  dengan fitur seleksi 30           :',knn_30_price_skor * 100 ,'%')
print('                                                                             ')
print('============= PACKAGING ================')
print('Nilai Model packaging K-NN pada K-50 tanpa seleksi                      :',knn_all_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 5633         :',knn_5633_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 3755         :',knn_3755_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 2253         :',knn_2253_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 376          :',knn_376_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 76           :',knn_76_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 30           :',knn_30_packaging_skor * 100 ,'%')
print('                                                                             ')
print('============= PRODUCT ================')
print('Nilai Model product K-NN pada K-50 tanpa seleksi                      :',knn_all_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 5633         :',knn_5633_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 3755         :',knn_3755_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 2253         :',knn_2253_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 376          :',knn_376_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 76           :',knn_76_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50  dengan fitur seleksi 30           :',knn_30_product_skor * 100 ,'%')
print('                                                                             ')
print('============= AROMA ================')
print('Nilai Model aroma K-NN pada K-50 tanpa seleksi                      :',knn_all_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 5633         :',knn_5633_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 3755         :',knn_3755_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 2253         :',knn_2253_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 376          :',knn_376_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 76           :',knn_76_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50  dengan fitur seleksi 30           :',knn_30_aroma_skor * 100 ,'%')


=============== PRICE ===================
Nilai Model price K-NN pada K-50 tanpa seleksi                      : 66.66666666666666 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 5633         : 52.90404040404041 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 3755         : 52.90404040404041 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 2253         : 52.90404040404041 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 376          : 52.90404040404041 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 76           : 53.40909090909091 %
Nilai Model price K-NN pada K-50  dengan fitur seleksi 30           : 49.24242424242424 %
                                                                             
============= PACKAGING ================
Nilai Model packaging K-NN pada K-50 tanpa seleksi                      : 84.84848484848484 %
Nilai Model packaging K-NN pada K-50  dengan fitur seleksi 5633         : 84.84848484848484 %
Nilai Model packaging

In [21]:
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
#from sklearn.metrics import  multilabel_confusion_matrix

In [22]:
#Evaluasi aspek Price Pada K = 7 tanpa seleksi
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_all)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_all)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_all, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_all, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_all, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_all, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_all, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_all, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_all, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_all, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_all, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_all, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 20 112  20]
 [  3 383  33]
 [  1  95 125]]

Accuracy: 0.67

Micro Precision: 0.67
Micro Recall: 0.67
Micro F1-score: 0.67

Macro Precision: 0.73
Macro Recall: 0.54
Macro F1-score: 0.54

Weighted Precision: 0.70
Weighted Recall: 0.67
Weighted F1-score: 0.62

Classification Report

              precision    recall  f1-score   support

          -1       0.83      0.13      0.23       152
           0       0.65      0.91      0.76       419
           1       0.70      0.57      0.63       221

    accuracy                           0.67       792
   macro avg       0.73      0.54      0.54       792
weighted avg       0.70      0.67      0.62       792



In [23]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 5633
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_5633)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_5633)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5633, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5633, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_5633, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5633, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5633, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_5633, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5633, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5633, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_5633, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_5633, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0 152   0]
 [  0 419   0]
 [  0 221   0]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.18
Macro Recall: 0.33
Macro F1-score: 0.23

Weighted Precision: 0.28
Weighted Recall: 0.53
Weighted F1-score: 0.37

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       152
           0       0.53      1.00      0.69       419
           1       0.00      0.00      0.00       221

    accuracy                           0.53       792
   macro avg       0.18      0.33      0.23       792
weighted avg       0.28      0.53      0.37       792



In [24]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 3755
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_3755)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_3755)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_3755, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_3755, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_3755, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_3755, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_3755, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_3755, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_3755, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_3755, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_3755, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_3755, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0 152   0]
 [  0 419   0]
 [  0 221   0]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.18
Macro Recall: 0.33
Macro F1-score: 0.23

Weighted Precision: 0.28
Weighted Recall: 0.53
Weighted F1-score: 0.37

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       152
           0       0.53      1.00      0.69       419
           1       0.00      0.00      0.00       221

    accuracy                           0.53       792
   macro avg       0.18      0.33      0.23       792
weighted avg       0.28      0.53      0.37       792



In [25]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 2253
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_2253)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_2253)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2253, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2253, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_2253, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2253, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2253, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_2253, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2253, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2253, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_2253, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_2253, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0 152   0]
 [  0 419   0]
 [  0 221   0]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.18
Macro Recall: 0.33
Macro F1-score: 0.23

Weighted Precision: 0.28
Weighted Recall: 0.53
Weighted F1-score: 0.37

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       152
           0       0.53      1.00      0.69       419
           1       0.00      0.00      0.00       221

    accuracy                           0.53       792
   macro avg       0.18      0.33      0.23       792
weighted avg       0.28      0.53      0.37       792



In [26]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 376
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_376)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_376)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_376, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_376, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_376, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_376, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_376, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_376, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_376, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_376, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_376, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_376, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0 152   0]
 [  0 419   0]
 [  1 220   0]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.18
Macro Recall: 0.33
Macro F1-score: 0.23

Weighted Precision: 0.28
Weighted Recall: 0.53
Weighted F1-score: 0.37

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       152
           0       0.53      1.00      0.69       419
           1       0.00      0.00      0.00       221

    accuracy                           0.53       792
   macro avg       0.18      0.33      0.23       792
weighted avg       0.28      0.53      0.37       792



In [27]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 76
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_76)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_76)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_76, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_76, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_76, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_76, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_76, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_76, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_76, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_76, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_76, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_76, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 11 130  11]
 [ 12 402   5]
 [  5 206  10]]

Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.44
Macro Recall: 0.36
Macro F1-score: 0.30

Weighted Precision: 0.47
Weighted Recall: 0.53
Weighted F1-score: 0.41

Classification Report

              precision    recall  f1-score   support

          -1       0.39      0.07      0.12       152
           0       0.54      0.96      0.69       419
           1       0.38      0.05      0.08       221

    accuracy                           0.53       792
   macro avg       0.44      0.36      0.30       792
weighted avg       0.47      0.53      0.41       792



In [51]:
#Evaluasi aspek Price Pada K = 7 dengan fitur seleksi 30
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_30)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_30)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_30, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_30, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_30, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_30, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_30, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_30, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_30, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_30, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_30, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_30, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2 122  28]
 [  2 383  34]
 [ 46 170   5]]

Accuracy: 0.49

Micro Precision: 0.49
Micro Recall: 0.49
Micro F1-score: 0.49

Macro Precision: 0.23
Macro Recall: 0.32
Macro F1-score: 0.25

Weighted Precision: 0.33
Weighted Recall: 0.49
Weighted F1-score: 0.38

Classification Report

              precision    recall  f1-score   support

          -1       0.04      0.01      0.02       152
           0       0.57      0.91      0.70       419
           1       0.07      0.02      0.03       221

    accuracy                           0.49       792
   macro avg       0.23      0.32      0.25       792
weighted avg       0.33      0.49      0.38       792



In [28]:
#Evaluasi aspek Packaging pada K= 7 tanpa seleksi
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_all)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_all)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_all, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_all, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_all, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_all, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_all, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_all, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_all, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_all, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_all, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_all, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  39   2]
 [  0 671   1]
 [  0  78   1]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.37
Macro Recall: 0.34
Macro F1-score: 0.31

Weighted Precision: 0.75
Weighted Recall: 0.85
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      1.00      0.92       672
           1       0.25      0.01      0.02        79

    accuracy                           0.85       792
   macro avg       0.37      0.34      0.31       792
weighted avg       0.75      0.85      0.78       792



In [29]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 5633
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_5633)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_5633)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5633, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5633, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_5633, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5633, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5633, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_5633, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5633, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5633, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_5633, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_5633, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  41   0]
 [  0 672   0]
 [  0  79   0]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.28
Macro Recall: 0.33
Macro F1-score: 0.31

Weighted Precision: 0.72
Weighted Recall: 0.85
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      1.00      0.92       672
           1       0.00      0.00      0.00        79

    accuracy                           0.85       792
   macro avg       0.28      0.33      0.31       792
weighted avg       0.72      0.85      0.78       792



In [30]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 3755
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_3755)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_3755)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_3755, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_3755, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_3755, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_3755, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_3755, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_3755, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_3755, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_3755, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_3755, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_3755, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  41   0]
 [  0 672   0]
 [  0  79   0]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.28
Macro Recall: 0.33
Macro F1-score: 0.31

Weighted Precision: 0.72
Weighted Recall: 0.85
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      1.00      0.92       672
           1       0.00      0.00      0.00        79

    accuracy                           0.85       792
   macro avg       0.28      0.33      0.31       792
weighted avg       0.72      0.85      0.78       792



In [31]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 2253
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_2253)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_2253)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2253, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2253, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_2253, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2253, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2253, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_2253, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2253, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2253, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_2253, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_2253, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  41   0]
 [  0 672   0]
 [  0  79   0]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.28
Macro Recall: 0.33
Macro F1-score: 0.31

Weighted Precision: 0.72
Weighted Recall: 0.85
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      1.00      0.92       672
           1       0.00      0.00      0.00        79

    accuracy                           0.85       792
   macro avg       0.28      0.33      0.31       792
weighted avg       0.72      0.85      0.78       792



In [32]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 376
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_376)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_376)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_376, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_376, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_376, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_376, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_376, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_376, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_376, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_376, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_376, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_376, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  41   0]
 [  0 671   1]
 [  0  79   0]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.28
Macro Recall: 0.33
Macro F1-score: 0.31

Weighted Precision: 0.72
Weighted Recall: 0.85
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.85      1.00      0.92       672
           1       0.00      0.00      0.00        79

    accuracy                           0.85       792
   macro avg       0.28      0.33      0.31       792
weighted avg       0.72      0.85      0.78       792



In [33]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 76
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_76)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_76)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_76, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_76, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_76, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_76, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_76, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_76, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_76, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_76, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_76, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_76, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  36   5]
 [  0 670   2]
 [  0  76   3]]

Accuracy: 0.85

Micro Precision: 0.85
Micro Recall: 0.85
Micro F1-score: 0.85

Macro Precision: 0.39
Macro Recall: 0.34
Macro F1-score: 0.33

Weighted Precision: 0.76
Weighted Recall: 0.85
Weighted F1-score: 0.79

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.86      1.00      0.92       672
           1       0.30      0.04      0.07        79

    accuracy                           0.85       792
   macro avg       0.39      0.34      0.33       792
weighted avg       0.76      0.85      0.79       792



In [52]:
#Evaluasi aspek Packaging pada K= 7 dengan fitur seleksi 30
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_30)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_30)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_30, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_30, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_30, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_30, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_30, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_30, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_30, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_30, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_30, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_30, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  36   5]
 [  0 667   5]
 [  0  77   2]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.34
Macro Recall: 0.34
Macro F1-score: 0.32

Weighted Precision: 0.74
Weighted Recall: 0.84
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.86      0.99      0.92       672
           1       0.17      0.03      0.04        79

    accuracy                           0.84       792
   macro avg       0.34      0.34      0.32       792
weighted avg       0.74      0.84      0.78       792



In [34]:
#Evaluasi aspek Product pada K= 7 tanpa seleksi
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_all)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_all)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_all, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_all, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_all, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_all, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_all, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_all, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_all, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_all, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_all, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_all, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 13   1 121]
 [  4  22  95]
 [  3   3 530]]

Accuracy: 0.71

Micro Precision: 0.71
Micro Recall: 0.71
Micro F1-score: 0.71

Macro Precision: 0.74
Macro Recall: 0.42
Macro F1-score: 0.43

Weighted Precision: 0.72
Weighted Recall: 0.71
Weighted F1-score: 0.63

Classification Report

              precision    recall  f1-score   support

          -1       0.65      0.10      0.17       135
           0       0.85      0.18      0.30       121
           1       0.71      0.99      0.83       536

    accuracy                           0.71       792
   macro avg       0.74      0.42      0.43       792
weighted avg       0.72      0.71      0.63       792



In [35]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 5633
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_5633)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_5633)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5633, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5633, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_5633, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5633, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5633, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_5633, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5633, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5633, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_5633, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_5633, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0   0 135]
 [  0   0 121]
 [  0   0 536]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.23
Macro Recall: 0.33
Macro F1-score: 0.27

Weighted Precision: 0.46
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.23      0.33      0.27       792
weighted avg       0.46      0.68      0.55       792



In [36]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 3755
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_3755)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_3755)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_3755, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_3755, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_3755, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_3755, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_3755, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_3755, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_3755, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_3755, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_3755, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_3755, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0   0 135]
 [  0   0 121]
 [  0   0 536]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.23
Macro Recall: 0.33
Macro F1-score: 0.27

Weighted Precision: 0.46
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.23      0.33      0.27       792
weighted avg       0.46      0.68      0.55       792



In [37]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 2253
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_2253)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_2253)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2253, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2253, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_2253, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2253, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2253, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_2253, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2253, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2253, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_2253, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_2253, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0   0 135]
 [  0   0 121]
 [  0   0 536]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.23
Macro Recall: 0.33
Macro F1-score: 0.27

Weighted Precision: 0.46
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.23      0.33      0.27       792
weighted avg       0.46      0.68      0.55       792



In [38]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 376
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_376)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_376)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_376, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_376, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_376, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_376, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_376, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_376, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_376, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_376, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_376, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_376, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0   0 135]
 [  0   0 121]
 [  0   0 536]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.23
Macro Recall: 0.33
Macro F1-score: 0.27

Weighted Precision: 0.46
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.23      0.33      0.27       792
weighted avg       0.46      0.68      0.55       792



In [39]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 76
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_76)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_76)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_76, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_76, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_76, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_76, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_76, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_76, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_76, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_76, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_76, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_76, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2   0 133]
 [  2   0 119]
 [  0   1 535]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.39
Macro Recall: 0.34
Macro F1-score: 0.28

Weighted Precision: 0.55
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.50      0.01      0.03       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.39      0.34      0.28       792
weighted avg       0.55      0.68      0.55       792



In [53]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 30
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_30)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_30)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_30, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_30, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_30, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_30, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_30, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_30, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_30, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_30, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_30, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_30, target_names=['-1', '0', '1']))

Confusion Matrix

[[  5   1 129]
 [ 10   6 105]
 [  3   0 533]]

Accuracy: 0.69

Micro Precision: 0.69
Micro Recall: 0.69
Micro F1-score: 0.69

Macro Precision: 0.61
Macro Recall: 0.36
Macro F1-score: 0.33

Weighted Precision: 0.65
Weighted Recall: 0.69
Weighted F1-score: 0.58

Classification Report

              precision    recall  f1-score   support

          -1       0.28      0.04      0.07       135
           0       0.86      0.05      0.09       121
           1       0.69      0.99      0.82       536

    accuracy                           0.69       792
   macro avg       0.61      0.36      0.33       792
weighted avg       0.65      0.69      0.58       792



In [40]:
#Evaluasi aspek Aroma pada K= 7 tanpa seleksi
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_all)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_all)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_all, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_all, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_all, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_all, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_all, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_all, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_all, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_all, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_all, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_all, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  38   2]
 [  0 612   3]
 [  0 118  19]]

Accuracy: 0.80

Micro Precision: 0.80
Micro Recall: 0.80
Micro F1-score: 0.80

Macro Precision: 0.53
Macro Recall: 0.38
Macro F1-score: 0.37

Weighted Precision: 0.76
Weighted Recall: 0.80
Weighted F1-score: 0.73

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.80      1.00      0.89       615
           1       0.79      0.14      0.24       137

    accuracy                           0.80       792
   macro avg       0.53      0.38      0.37       792
weighted avg       0.76      0.80      0.73       792



In [41]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 5633
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_5633)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_5633)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5633, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5633, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_5633, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5633, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5633, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_5633, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5633, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5633, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_5633, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_5633, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  40   0]
 [  0 615   0]
 [  0 137   0]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.26
Macro Recall: 0.33
Macro F1-score: 0.29

Weighted Precision: 0.60
Weighted Recall: 0.78
Weighted F1-score: 0.68

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.78      1.00      0.87       615
           1       0.00      0.00      0.00       137

    accuracy                           0.78       792
   macro avg       0.26      0.33      0.29       792
weighted avg       0.60      0.78      0.68       792



In [42]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 3755
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_3755)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_3755)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_3755, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_3755, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_3755, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_3755, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_3755, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_3755, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_3755, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_3755, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_3755, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_3755, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  40   0]
 [  0 615   0]
 [  0 137   0]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.26
Macro Recall: 0.33
Macro F1-score: 0.29

Weighted Precision: 0.60
Weighted Recall: 0.78
Weighted F1-score: 0.68

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.78      1.00      0.87       615
           1       0.00      0.00      0.00       137

    accuracy                           0.78       792
   macro avg       0.26      0.33      0.29       792
weighted avg       0.60      0.78      0.68       792



In [43]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 2253
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_2253)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_2253)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2253, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2253, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_2253, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2253, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2253, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_2253, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2253, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2253, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_2253, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_2253, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  40   0]
 [  0 615   0]
 [  0 137   0]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.26
Macro Recall: 0.33
Macro F1-score: 0.29

Weighted Precision: 0.60
Weighted Recall: 0.78
Weighted F1-score: 0.68

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.78      1.00      0.87       615
           1       0.00      0.00      0.00       137

    accuracy                           0.78       792
   macro avg       0.26      0.33      0.29       792
weighted avg       0.60      0.78      0.68       792



In [44]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 376
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_376)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_376)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_376, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_376, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_376, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_376, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_376, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_376, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_376, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_376, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_376, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_376, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  39   1]
 [  0 615   0]
 [  0 136   1]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.43
Macro Recall: 0.34
Macro F1-score: 0.30

Weighted Precision: 0.69
Weighted Recall: 0.78
Weighted F1-score: 0.68

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.78      1.00      0.88       615
           1       0.50      0.01      0.01       137

    accuracy                           0.78       792
   macro avg       0.43      0.34      0.30       792
weighted avg       0.69      0.78      0.68       792



In [45]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 76
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_76)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_76)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_76, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_76, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_76, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_76, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_76, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_76, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_76, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_76, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_76, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_76, target_names=['-1', '0', '1']))

Confusion Matrix

[[  1  36   3]
 [  0 614   1]
 [  0 123  14]]

Accuracy: 0.79

Micro Precision: 0.79
Micro Recall: 0.79
Micro F1-score: 0.79

Macro Precision: 0.86
Macro Recall: 0.38
Macro F1-score: 0.37

Weighted Precision: 0.80
Weighted Recall: 0.79
Weighted F1-score: 0.72

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.03      0.05        40
           0       0.79      1.00      0.88       615
           1       0.78      0.10      0.18       137

    accuracy                           0.79       792
   macro avg       0.86      0.38      0.37       792
weighted avg       0.80      0.79      0.72       792



In [54]:
#Evaluasi aspek Product pada K= 7 dengan fitur seleksi 30
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_30)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_30)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_30, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_30, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_30, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_30, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_30, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_30, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_30, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_30, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_30, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_30, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  31   9]
 [  0 593  22]
 [  0 123  14]]

Accuracy: 0.77

Micro Precision: 0.77
Micro Recall: 0.77
Micro F1-score: 0.77

Macro Precision: 0.37
Macro Recall: 0.36
Macro F1-score: 0.34

Weighted Precision: 0.67
Weighted Recall: 0.77
Weighted F1-score: 0.70

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        40
           0       0.79      0.96      0.87       615
           1       0.31      0.10      0.15       137

    accuracy                           0.77       792
   macro avg       0.37      0.36      0.34       792
weighted avg       0.67      0.77      0.70       792

