In [1]:
import pandas as pd
import numpy as np

import pickle

from sklearn.feature_extraction.text import TfidfVectorizer 

from sklearn.svm import SVC 

import warnings
warnings.filterwarnings("ignore")

In [2]:
data_train = pd.read_csv('data_train_lengkap.csv', sep=';')
data_test = pd.read_csv('data_test_lengkap.csv', sep=';')

In [3]:
data_train.head()

review_text  price  packaging  \
0  dair penasaran banget skincare reviewnya banya...     -1          0   
1  ngincer bilang dupenya ski baca review tertawa...      0          0   
2  suka tabirsurya tekstur ringan serap banget ku...      0          1   
3  nyobain pas muka lagi stress ny desperate bang...      0          0   
4  suka gokujyun losion merek hada labo lotionnya...      1          0   

   product  aroma  
0      0.0      0  
1      1.0      0  
2      1.0      0  
3     -1.0      0  
4      1.0      0

In [4]:
data_test.head()

review_text  price  packaging  \
0  produk favorit banget enak dipake plus tidak r...     -1          0   
1  lengket pas dipake hitungan tabirsurya yang ti...      1          0   
2  minyak kontrol lumayan ngempesin jerawat efek ...      1          0   
3  favorite banget harga terjangkau banget gak ha...      1          0   
4  exfoliant toner pakai bagi step double toning ...      0          0   

   product  aroma  
0      1.0      0  
1      0.0      0  
2     -1.0      0  
3      1.0      0  
4      1.0      0

In [5]:
data_train.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [6]:
data_test.isnull().sum()

review_text    0
price          0
packaging      0
product        0
aroma          0
dtype: int64

In [7]:
X_train = data_train['review_text']
X_test = data_test['review_text']

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
fitur_train = TfidfVectorizer().fit(X_train)
tfidf_train = fitur_train.transform(X_train).toarray()
tfidf_test = fitur_train.transform(X_test).toarray()

In [9]:
def get_fitur_tfidf(tfidf, fitur):
    terms = tfidf.get_feature_names()
    sums = fitur.sum(axis = 0)

    data = []
    for col, term in enumerate(terms):
        data.append((term, sums[col] ))
    ranking = pd.DataFrame(data, columns=['Terms','TF-IDF'])
    return ranking

In [10]:
out_tfidf_tr = get_fitur_tfidf(fitur_train, tfidf_train)

In [11]:
out_tfidf_tr.shape

(7361, 2)

In [12]:
#FEATURE SELECTION CHI SQUARE
from sklearn import datasets
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [13]:
x_chi_tr = tfidf_train
x_chi_test = tfidf_test

In [14]:
#y_chi_tr = np.array(data_train[['price','packaging','aroma','product']])
#y_chi_test = np.array(data_test[['price','packaging','aroma','product']])

In [15]:
y_price_tr = (data_train['price'])
y_packaging_tr = (data_train['packaging'])
y_product_tr = (data_train['product'])
y_aroma_tr = (data_train['aroma'])

In [16]:
y_price_test = (data_test['price'])
y_packaging_test = (data_test['packaging'])
y_product_test = (data_test['product'])
y_aroma_test = (data_test['aroma'])

In [17]:
chi_price_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_price_tr)
chi_packaging_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_packaging_tr)
chi_product_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_product_tr)
chi_aroma_tr = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_tr, y_aroma_tr)


chi_price_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_price_test)
chi_packaging_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_packaging_test)
chi_product_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_product_test)
chi_aroma_test = SelectKBest(score_func=chi2, k=76).fit_transform(x_chi_test, y_aroma_test)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

#aspek price
knn_price_2 = KNeighborsClassifier(n_neighbors=2)
knn_price_5 = KNeighborsClassifier(n_neighbors=5)
knn_price_7 = KNeighborsClassifier(n_neighbors=7)
knn_price_9 = KNeighborsClassifier(n_neighbors=9)
knn_price_13 = KNeighborsClassifier(n_neighbors=13)
knn_price_20 = KNeighborsClassifier(n_neighbors=20)
knn_price_50 = KNeighborsClassifier(n_neighbors=50)

knn_price_2.fit(chi_price_tr, y_price_tr)
knn_price_5.fit(chi_price_tr, y_price_tr)
knn_price_7.fit(chi_price_tr, y_price_tr)
knn_price_9.fit(chi_price_tr, y_price_tr)
knn_price_13.fit(chi_price_tr, y_price_tr)
knn_price_20.fit(chi_price_tr, y_price_tr)
knn_price_50.fit(chi_price_tr, y_price_tr)

predictions_price_2 = knn_price_2.predict(chi_price_test)
predictions_price_5 = knn_price_5.predict(chi_price_test)
predictions_price_7 = knn_price_7.predict(chi_price_test)
predictions_price_9 = knn_price_9.predict(chi_price_test)
predictions_price_13 = knn_price_13.predict(chi_price_test)
predictions_price_20 = knn_price_20.predict(chi_price_test)
predictions_price_50 = knn_price_50.predict(chi_price_test)

#aspek packaging
knn_packaging_2 = KNeighborsClassifier(n_neighbors=2)
knn_packaging_5 = KNeighborsClassifier(n_neighbors=5)
knn_packaging_7 = KNeighborsClassifier(n_neighbors=7)
knn_packaging_9 = KNeighborsClassifier(n_neighbors=9)
knn_packaging_13 = KNeighborsClassifier(n_neighbors=13)
knn_packaging_20 = KNeighborsClassifier(n_neighbors=20)
knn_packaging_50 = KNeighborsClassifier(n_neighbors=50)

knn_packaging_2.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_5.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_7.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_9.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_13.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_20.fit(chi_packaging_tr, y_packaging_tr)
knn_packaging_50.fit(chi_packaging_tr, y_packaging_tr)

predictions_packaging_2 = knn_packaging_2.predict(chi_packaging_test)
predictions_packaging_5 = knn_packaging_5.predict(chi_packaging_test)
predictions_packaging_7 = knn_packaging_7.predict(chi_packaging_test)
predictions_packaging_9 = knn_packaging_9.predict(chi_packaging_test)
predictions_packaging_13 = knn_packaging_13.predict(chi_packaging_test)
predictions_packaging_20 = knn_packaging_20.predict(chi_packaging_test)
predictions_packaging_50 = knn_packaging_50.predict(chi_packaging_test)

#aspek product
knn_product_2 = KNeighborsClassifier(n_neighbors=2)
knn_product_5 = KNeighborsClassifier(n_neighbors=5)
knn_product_7 = KNeighborsClassifier(n_neighbors=7)
knn_product_9 = KNeighborsClassifier(n_neighbors=9)
knn_product_13 = KNeighborsClassifier(n_neighbors=13)
knn_product_20 = KNeighborsClassifier(n_neighbors=20)
knn_product_50 = KNeighborsClassifier(n_neighbors=50)

knn_product_2.fit(chi_product_tr, y_product_tr)
knn_product_5.fit(chi_product_tr, y_product_tr)
knn_product_7.fit(chi_product_tr, y_product_tr)
knn_product_9.fit(chi_product_tr, y_product_tr)
knn_product_13.fit(chi_product_tr, y_product_tr)
knn_product_20.fit(chi_product_tr, y_product_tr)
knn_product_50.fit(chi_product_tr, y_product_tr)

predictions_product_2 = knn_product_2.predict(chi_product_test)
predictions_product_5 = knn_product_5.predict(chi_product_test)
predictions_product_7 = knn_product_7.predict(chi_product_test)
predictions_product_9 = knn_product_9.predict(chi_product_test)
predictions_product_13 = knn_product_13.predict(chi_product_test)
predictions_product_20 = knn_product_20.predict(chi_product_test)
predictions_product_50 = knn_product_50.predict(chi_product_test)

#aspek aroma
knn_aroma_2 = KNeighborsClassifier(n_neighbors=2)
knn_aroma_5 = KNeighborsClassifier(n_neighbors=5)
knn_aroma_7 = KNeighborsClassifier(n_neighbors=7)
knn_aroma_9 = KNeighborsClassifier(n_neighbors=9)
knn_aroma_13 = KNeighborsClassifier(n_neighbors=13)
knn_aroma_20 = KNeighborsClassifier(n_neighbors=20)
knn_aroma_50 = KNeighborsClassifier(n_neighbors=50)

knn_aroma_2.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_5.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_7.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_9.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_13.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_20.fit(chi_aroma_tr, y_aroma_tr)
knn_aroma_50.fit(chi_aroma_tr, y_aroma_tr)

predictions_aroma_2 = knn_aroma_2.predict(chi_aroma_test)
predictions_aroma_5 = knn_aroma_5.predict(chi_aroma_test)
predictions_aroma_7 = knn_aroma_7.predict(chi_aroma_test)
predictions_aroma_9 = knn_aroma_9.predict(chi_aroma_test)
predictions_aroma_13 = knn_aroma_13.predict(chi_aroma_test)
predictions_aroma_20 = knn_aroma_20.predict(chi_aroma_test)
predictions_aroma_50 = knn_aroma_50.predict(chi_aroma_test)

In [19]:
#Nilai price
knn2_price_skor=knn_price_2.score(chi_price_test,y_price_test)
knn5_price_skor=knn_price_5.score(chi_price_test,y_price_test)
knn7_price_skor=knn_price_7.score(chi_price_test,y_price_test)
knn9_price_skor=knn_price_9.score(chi_price_test,y_price_test)
knn13_price_skor=knn_price_13.score(chi_price_test,y_price_test)
knn20_price_skor=knn_price_20.score(chi_price_test,y_price_test)
knn50_price_skor=knn_price_50.score(chi_price_test,y_price_test)

#nilai packaging
knn2_packaging_skor=knn_packaging_2.score(chi_packaging_test,y_packaging_test)
knn5_packaging_skor=knn_packaging_5.score(chi_packaging_test,y_packaging_test)
knn7_packaging_skor=knn_packaging_7.score(chi_packaging_test,y_packaging_test)
knn9_packaging_skor=knn_packaging_9.score(chi_packaging_test,y_packaging_test)
knn13_packaging_skor=knn_packaging_13.score(chi_packaging_test,y_packaging_test)
knn20_packaging_skor=knn_packaging_20.score(chi_packaging_test,y_packaging_test)
knn50_packaging_skor=knn_packaging_50.score(chi_packaging_test,y_packaging_test)

#nilai product
knn2_product_skor=knn_product_2.score(chi_product_test,y_product_test)
knn5_product_skor=knn_product_5.score(chi_product_test,y_product_test)
knn7_product_skor=knn_product_7.score(chi_product_test,y_product_test)
knn9_product_skor=knn_product_9.score(chi_product_test,y_product_test)
knn13_product_skor=knn_product_13.score(chi_product_test,y_product_test)
knn20_product_skor=knn_product_20.score(chi_product_test,y_product_test)
knn50_product_skor=knn_product_50.score(chi_product_test,y_product_test)

#nilai aroma
knn2_aroma_skor=knn_aroma_2.score(chi_aroma_test,y_aroma_test)
knn5_aroma_skor=knn_aroma_5.score(chi_aroma_test,y_aroma_test)
knn7_aroma_skor=knn_aroma_7.score(chi_aroma_test,y_aroma_test)
knn9_aroma_skor=knn_aroma_9.score(chi_aroma_test,y_aroma_test)
knn13_aroma_skor=knn_aroma_13.score(chi_aroma_test,y_aroma_test)
knn20_aroma_skor=knn_aroma_20.score(chi_aroma_test,y_aroma_test)
knn50_aroma_skor=knn_aroma_50.score(chi_aroma_test,y_aroma_test)

print('=============== PRICE ===================')
print('Nilai Model price K-NN pada K-2           :',knn2_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-5           :',knn5_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-7           :',knn7_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-9           :',knn9_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-13          :',knn13_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-20          :',knn20_price_skor * 100 ,'%')
print('Nilai Model price K-NN pada K-50          :',knn50_price_skor * 100 ,'%')
print('                                                                             ')
print('============= PACKAGING ================')
print('Nilai Model packaging K-NN pada K-2       :',knn2_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-5       :',knn5_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-7       :',knn7_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-9       :',knn9_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-13      :',knn13_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-20      :',knn20_packaging_skor * 100 ,'%')
print('Nilai Model packaging K-NN pada K-50      :',knn50_packaging_skor * 100 ,'%')
print('                                                                             ')
print('============= PRODUCT ================')
print('Nilai Model product K-NN pada K-2         :',knn2_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-5         :',knn5_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-7         :',knn7_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-9         :',knn9_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-13        :',knn13_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-20        :',knn20_product_skor * 100 ,'%')
print('Nilai Model product K-NN pada K-50        :',knn50_product_skor * 100 ,'%')
print('                                                                             ')
print('============= AROMA ================')
print('Nilai Model aroma K-NN pada K-2           :',knn2_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-5           :',knn5_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-7           :',knn7_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-9           :',knn9_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-13          :',knn13_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-20          :',knn20_aroma_skor * 100 ,'%')
print('Nilai Model aroma K-NN pada K-50          :',knn50_aroma_skor * 100 ,'%')

=============== PRICE ===================
Nilai Model price K-NN pada K-2           : 51.13636363636363 %
Nilai Model price K-NN pada K-5           : 50.63131313131313 %
Nilai Model price K-NN pada K-7           : 50.88383838383839 %
Nilai Model price K-NN pada K-9           : 51.26262626262626 %
Nilai Model price K-NN pada K-13          : 50.378787878787875 %
Nilai Model price K-NN pada K-20          : 51.13636363636363 %
Nilai Model price K-NN pada K-50          : 52.3989898989899 %
                                                                             
============= PACKAGING ================
Nilai Model packaging K-NN pada K-2       : 83.83838383838383 %
Nilai Model packaging K-NN pada K-5       : 84.21717171717171 %
Nilai Model packaging K-NN pada K-7       : 84.34343434343434 %
Nilai Model packaging K-NN pada K-9       : 84.21717171717171 %
Nilai Model packaging K-NN pada K-13      : 84.0909090909091 %
Nilai Model packaging K-NN pada K-20      : 84.0909090909091 %
Nilai Mod

In [20]:
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
#from sklearn.metrics import  multilabel_confusion_matrix

In [21]:
#Evaluasi aspek Price Pada K = 2
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_2)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_2)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_2, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_2, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_2, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_2, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_2, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_2, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 36 100  16]
 [ 61 347  11]
 [ 50 149  22]]

Accuracy: 0.51

Micro Precision: 0.51
Micro Recall: 0.51
Micro F1-score: 0.51

Macro Precision: 0.43
Macro Recall: 0.39
Macro F1-score: 0.36

Weighted Precision: 0.48
Weighted Recall: 0.51
Weighted F1-score: 0.45

Classification Report

              precision    recall  f1-score   support

          -1       0.24      0.24      0.24       152
           0       0.58      0.83      0.68       419
           1       0.45      0.10      0.16       221

    accuracy                           0.51       792
   macro avg       0.43      0.39      0.36       792
weighted avg       0.48      0.51      0.45       792



In [22]:
#Evaluasi aspek Price Pada K = 5
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_5)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_5)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_5, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_5, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_5, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_5, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_5, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_5, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 23 106  23]
 [ 36 352  31]
 [ 24 171  26]]

Accuracy: 0.51

Micro Precision: 0.51
Micro Recall: 0.51
Micro F1-score: 0.51

Macro Precision: 0.39
Macro Recall: 0.37
Macro F1-score: 0.35

Weighted Precision: 0.44
Weighted Recall: 0.51
Weighted F1-score: 0.44

Classification Report

              precision    recall  f1-score   support

          -1       0.28      0.15      0.20       152
           0       0.56      0.84      0.67       419
           1       0.33      0.12      0.17       221

    accuracy                           0.51       792
   macro avg       0.39      0.37      0.35       792
weighted avg       0.44      0.51      0.44       792



In [23]:
#Evaluasi aspek Price Pada K = 7
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 23 108  21]
 [ 27 361  31]
 [ 23 179  19]]

Accuracy: 0.51

Micro Precision: 0.51
Micro Recall: 0.51
Micro F1-score: 0.51

Macro Precision: 0.38
Macro Recall: 0.37
Macro F1-score: 0.34

Weighted Precision: 0.43
Weighted Recall: 0.51
Weighted F1-score: 0.43

Classification Report

              precision    recall  f1-score   support

          -1       0.32      0.15      0.20       152
           0       0.56      0.86      0.68       419
           1       0.27      0.09      0.13       221

    accuracy                           0.51       792
   macro avg       0.38      0.37      0.34       792
weighted avg       0.43      0.51      0.43       792



In [24]:
#Evaluasi aspek Price Pada K = 9
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_9)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_9)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_9, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_9, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_9, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_9, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_9, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_9, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_9, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_9, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_9, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_9, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 23 113  16]
 [ 26 366  27]
 [ 23 181  17]]

Accuracy: 0.51

Micro Precision: 0.51
Micro Recall: 0.51
Micro F1-score: 0.51

Macro Precision: 0.39
Macro Recall: 0.37
Macro F1-score: 0.33

Weighted Precision: 0.43
Weighted Recall: 0.51
Weighted F1-score: 0.43

Classification Report

              precision    recall  f1-score   support

          -1       0.32      0.15      0.21       152
           0       0.55      0.87      0.68       419
           1       0.28      0.08      0.12       221

    accuracy                           0.51       792
   macro avg       0.39      0.37      0.33       792
weighted avg       0.43      0.51      0.43       792



In [25]:
#Evaluasi aspek Price Pada K = 13
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_13)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_13)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_13, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_13, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_13, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_13, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_13, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_13, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_13, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_13, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_13, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_13, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 19 119  14]
 [ 31 370  18]
 [ 22 189  10]]

Accuracy: 0.50

Micro Precision: 0.50
Micro Recall: 0.50
Micro F1-score: 0.50

Macro Precision: 0.35
Macro Recall: 0.35
Macro F1-score: 0.31

Weighted Precision: 0.41
Weighted Recall: 0.50
Weighted F1-score: 0.41

Classification Report

              precision    recall  f1-score   support

          -1       0.26      0.12      0.17       152
           0       0.55      0.88      0.67       419
           1       0.24      0.05      0.08       221

    accuracy                           0.50       792
   macro avg       0.35      0.35      0.31       792
weighted avg       0.41      0.50      0.41       792



In [26]:
#Evaluasi aspek Price Pada K = 20
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_20)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_20)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_20, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_20, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_20, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_20, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_20, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_20, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_20, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_20, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_20, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_20, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 14 125  13]
 [ 26 381  12]
 [ 21 190  10]]

Accuracy: 0.51

Micro Precision: 0.51
Micro Recall: 0.51
Micro F1-score: 0.51

Macro Precision: 0.35
Macro Recall: 0.35
Macro F1-score: 0.30

Weighted Precision: 0.41
Weighted Recall: 0.51
Weighted F1-score: 0.41

Classification Report

              precision    recall  f1-score   support

          -1       0.23      0.09      0.13       152
           0       0.55      0.91      0.68       419
           1       0.29      0.05      0.08       221

    accuracy                           0.51       792
   macro avg       0.35      0.35      0.30       792
weighted avg       0.41      0.51      0.41       792



In [27]:
#Evaluasi aspek Price Pada K = 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_price_test,predictions_price_50)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_price_test,predictions_price_50)))

print('Micro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_50, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_50, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_50, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_50, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_50, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_price_test,predictions_price_50, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_price_test,predictions_price_50, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_price_test,predictions_price_50, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_price_test,predictions_price_50, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_price_test,predictions_price_50, target_names=['-1', '0', '1']))

Confusion Matrix

[[  9 136   7]
 [  9 400  10]
 [ 18 197   6]]

Accuracy: 0.52

Micro Precision: 0.52
Micro Recall: 0.52
Micro F1-score: 0.52

Macro Precision: 0.35
Macro Recall: 0.35
Macro F1-score: 0.28

Weighted Precision: 0.41
Weighted Recall: 0.52
Weighted F1-score: 0.40

Classification Report

              precision    recall  f1-score   support

          -1       0.25      0.06      0.10       152
           0       0.55      0.95      0.69       419
           1       0.26      0.03      0.05       221

    accuracy                           0.52       792
   macro avg       0.35      0.35      0.28       792
weighted avg       0.41      0.52      0.40       792



In [28]:
#Evaluasi aspek Packaging pada K= 2
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_2)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_2)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_2, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_2, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_2, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_2, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_2, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_2, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 10  27   4]
 [ 10 649  13]
 [ 19  55   5]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.46
Macro Recall: 0.42
Macro F1-score: 0.42

Weighted Precision: 0.79
Weighted Recall: 0.84
Weighted F1-score: 0.81

Classification Report

              precision    recall  f1-score   support

          -1       0.26      0.24      0.25        41
           0       0.89      0.97      0.93       672
           1       0.23      0.06      0.10        79

    accuracy                           0.84       792
   macro avg       0.46      0.42      0.42       792
weighted avg       0.79      0.84      0.81       792



In [29]:
#Evaluasi aspek Packaging pada K= 5
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_5)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_5)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_5, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_5, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_5, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_5, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_5, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_5, target_names=['-1', '0', '1']))

Confusion Matrix

[[  5  29   7]
 [  1 655  16]
 [  4  68   7]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.53
Macro Recall: 0.40
Macro F1-score: 0.41

Weighted Precision: 0.79
Weighted Recall: 0.84
Weighted F1-score: 0.80

Classification Report

              precision    recall  f1-score   support

          -1       0.50      0.12      0.20        41
           0       0.87      0.97      0.92       672
           1       0.23      0.09      0.13        79

    accuracy                           0.84       792
   macro avg       0.53      0.40      0.41       792
weighted avg       0.79      0.84      0.80       792



In [30]:
#Evaluasi aspek Packaging pada K= 7
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2  32   7]
 [  0 657  15]
 [  0  70   9]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.72
Macro Recall: 0.38
Macro F1-score: 0.39

Weighted Precision: 0.82
Weighted Recall: 0.84
Weighted F1-score: 0.80

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.05      0.09        41
           0       0.87      0.98      0.92       672
           1       0.29      0.11      0.16        79

    accuracy                           0.84       792
   macro avg       0.72      0.38      0.39       792
weighted avg       0.82      0.84      0.80       792



In [31]:
#Evaluasi aspek Packaging pada K= 9
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_9)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_9)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_9, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_9, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_9, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_9, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_9, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_9, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_9, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_9, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_9, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_9, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2  32   7]
 [  0 657  15]
 [  0  71   8]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.71
Macro Recall: 0.38
Macro F1-score: 0.39

Weighted Precision: 0.81
Weighted Recall: 0.84
Weighted F1-score: 0.80

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.05      0.09        41
           0       0.86      0.98      0.92       672
           1       0.27      0.10      0.15        79

    accuracy                           0.84       792
   macro avg       0.71      0.38      0.39       792
weighted avg       0.81      0.84      0.80       792



In [32]:
#Evaluasi aspek Packaging pada K= 13
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_13)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_13)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_13, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_13, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_13, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_13, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_13, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_13, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_13, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_13, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_13, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_13, target_names=['-1', '0', '1']))

Confusion Matrix

[[  1  31   9]
 [  0 657  15]
 [  0  71   8]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.71
Macro Recall: 0.37
Macro F1-score: 0.37

Weighted Precision: 0.81
Weighted Recall: 0.84
Weighted F1-score: 0.80

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.02      0.05        41
           0       0.87      0.98      0.92       672
           1       0.25      0.10      0.14        79

    accuracy                           0.84       792
   macro avg       0.71      0.37      0.37       792
weighted avg       0.81      0.84      0.80       792



In [33]:
#Evaluasi aspek Packaging pada K= 20
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_20)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_20)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_20, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_20, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_20, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_20, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_20, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_20, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_20, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_20, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_20, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_20, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  32   9]
 [  0 657  15]
 [  0  70   9]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.38
Macro Recall: 0.36
Macro F1-score: 0.36

Weighted Precision: 0.76
Weighted Recall: 0.84
Weighted F1-score: 0.80

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.87      0.98      0.92       672
           1       0.27      0.11      0.16        79

    accuracy                           0.84       792
   macro avg       0.38      0.36      0.36       792
weighted avg       0.76      0.84      0.80       792



In [34]:
#Evaluasi aspek Packaging pada K= 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_packaging_test,predictions_packaging_50)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_packaging_test,predictions_packaging_50)))

print('Micro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_50, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_50, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_50, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_50, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_50, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_packaging_test,predictions_packaging_50, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_packaging_test,predictions_packaging_50, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_packaging_test,predictions_packaging_50, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_packaging_test,predictions_packaging_50, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_packaging_test,predictions_packaging_50, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0  36   5]
 [  0 659  13]
 [  0  75   4]]

Accuracy: 0.84

Micro Precision: 0.84
Micro Recall: 0.84
Micro F1-score: 0.84

Macro Precision: 0.35
Macro Recall: 0.34
Macro F1-score: 0.33

Weighted Precision: 0.74
Weighted Recall: 0.84
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        41
           0       0.86      0.98      0.91       672
           1       0.18      0.05      0.08        79

    accuracy                           0.84       792
   macro avg       0.35      0.34      0.33       792
weighted avg       0.74      0.84      0.78       792



In [35]:
#Evaluasi aspek Product pada K= 2
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_2)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_2)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_2, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_2, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_2, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_2, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_2, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_2, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 56  29  50]
 [ 41  26  54]
 [203 100 233]]

Accuracy: 0.40

Micro Precision: 0.40
Micro Recall: 0.40
Micro F1-score: 0.40

Macro Precision: 0.35
Macro Recall: 0.35
Macro F1-score: 0.33

Weighted Precision: 0.53
Weighted Recall: 0.40
Weighted F1-score: 0.43

Classification Report

              precision    recall  f1-score   support

          -1       0.19      0.41      0.26       135
           0       0.17      0.21      0.19       121
           1       0.69      0.43      0.53       536

    accuracy                           0.40       792
   macro avg       0.35      0.35      0.33       792
weighted avg       0.53      0.40      0.43       792



In [36]:
#Evaluasi aspek Product pada K= 5
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_5)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_5)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_5, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_5, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_5, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_5, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_5, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_5, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 28  18  89]
 [ 24  19  78]
 [ 95  52 389]]

Accuracy: 0.55

Micro Precision: 0.55
Micro Recall: 0.55
Micro F1-score: 0.55

Macro Precision: 0.37
Macro Recall: 0.36
Macro F1-score: 0.36

Weighted Precision: 0.54
Weighted Recall: 0.55
Weighted F1-score: 0.54

Classification Report

              precision    recall  f1-score   support

          -1       0.19      0.21      0.20       135
           0       0.21      0.16      0.18       121
           1       0.70      0.73      0.71       536

    accuracy                           0.55       792
   macro avg       0.37      0.36      0.36       792
weighted avg       0.54      0.55      0.54       792



In [37]:
#Evaluasi aspek Product pada K= 7
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 29  10  96]
 [ 19  15  87]
 [ 60  30 446]]

Accuracy: 0.62

Micro Precision: 0.62
Micro Recall: 0.62
Micro F1-score: 0.62

Macro Precision: 0.42
Macro Recall: 0.39
Macro F1-score: 0.39

Weighted Precision: 0.57
Weighted Recall: 0.62
Weighted F1-score: 0.58

Classification Report

              precision    recall  f1-score   support

          -1       0.27      0.21      0.24       135
           0       0.27      0.12      0.17       121
           1       0.71      0.83      0.77       536

    accuracy                           0.62       792
   macro avg       0.42      0.39      0.39       792
weighted avg       0.57      0.62      0.58       792



In [38]:
#Evaluasi aspek Product pada K= 9
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_9)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_9)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_9, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_9, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_9, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_9, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_9, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_9, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_9, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_9, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_9, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_9, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 22   9 104]
 [ 15  10  96]
 [ 51  11 474]]

Accuracy: 0.64

Micro Precision: 0.64
Micro Recall: 0.64
Micro F1-score: 0.64

Macro Precision: 0.43
Macro Recall: 0.38
Macro F1-score: 0.37

Weighted Precision: 0.57
Weighted Recall: 0.64
Weighted F1-score: 0.58

Classification Report

              precision    recall  f1-score   support

          -1       0.25      0.16      0.20       135
           0       0.33      0.08      0.13       121
           1       0.70      0.88      0.78       536

    accuracy                           0.64       792
   macro avg       0.43      0.38      0.37       792
weighted avg       0.57      0.64      0.58       792



In [39]:
#Evaluasi aspek Product pada K= 13
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_13)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_13)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_13, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_13, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_13, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_13, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_13, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_13, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_13, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_13, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_13, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_13, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 20   7 108]
 [ 12   5 104]
 [ 62   9 465]]

Accuracy: 0.62

Micro Precision: 0.62
Micro Recall: 0.62
Micro F1-score: 0.62

Macro Precision: 0.38
Macro Recall: 0.35
Macro F1-score: 0.34

Weighted Precision: 0.54
Weighted Recall: 0.62
Weighted F1-score: 0.56

Classification Report

              precision    recall  f1-score   support

          -1       0.21      0.15      0.17       135
           0       0.24      0.04      0.07       121
           1       0.69      0.87      0.77       536

    accuracy                           0.62       792
   macro avg       0.38      0.35      0.34       792
weighted avg       0.54      0.62      0.56       792



In [40]:
#Evaluasi aspek Product pada K= 20
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_20)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_20)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_20, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_20, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_20, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_20, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_20, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_20, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_20, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_20, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_20, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_20, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 13   4 118]
 [  7   4 110]
 [ 18   7 511]]

Accuracy: 0.67

Micro Precision: 0.67
Micro Recall: 0.67
Micro F1-score: 0.67

Macro Precision: 0.43
Macro Recall: 0.36
Macro F1-score: 0.34

Weighted Precision: 0.57
Weighted Recall: 0.67
Weighted F1-score: 0.58

Classification Report

              precision    recall  f1-score   support

          -1       0.34      0.10      0.15       135
           0       0.27      0.03      0.06       121
           1       0.69      0.95      0.80       536

    accuracy                           0.67       792
   macro avg       0.43      0.36      0.34       792
weighted avg       0.57      0.67      0.58       792



In [41]:
#Evaluasi aspek Product pada K= 50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_product_test,predictions_product_50)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_product_test,predictions_product_50)))

print('Micro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_50, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_50, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_50, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_50, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_50, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_product_test,predictions_product_50, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_product_test,predictions_product_50, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_product_test,predictions_product_50, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_product_test,predictions_product_50, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_product_test,predictions_product_50, target_names=['-1', '0', '1']))

Confusion Matrix

[[  0   0 135]
 [  2   0 119]
 [  0   1 535]]

Accuracy: 0.68

Micro Precision: 0.68
Micro Recall: 0.68
Micro F1-score: 0.68

Macro Precision: 0.23
Macro Recall: 0.33
Macro F1-score: 0.27

Weighted Precision: 0.46
Weighted Recall: 0.68
Weighted F1-score: 0.55

Classification Report

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       135
           0       0.00      0.00      0.00       121
           1       0.68      1.00      0.81       536

    accuracy                           0.68       792
   macro avg       0.23      0.33      0.27       792
weighted avg       0.46      0.68      0.55       792



In [42]:
#Evaluasi aspek Aroma Pada K=2
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_2)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_2)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_2, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_2, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_2, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_2, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_2, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_2, target_names=['-1', '0', '1']))

Confusion Matrix

[[ 12  25   3]
 [ 14 590  11]
 [ 22 110   5]]

Accuracy: 0.77

Micro Precision: 0.77
Micro Recall: 0.77
Micro F1-score: 0.77

Macro Precision: 0.44
Macro Recall: 0.43
Macro F1-score: 0.41

Weighted Precision: 0.69
Weighted Recall: 0.77
Weighted F1-score: 0.71

Classification Report

              precision    recall  f1-score   support

          -1       0.25      0.30      0.27        40
           0       0.81      0.96      0.88       615
           1       0.26      0.04      0.06       137

    accuracy                           0.77       792
   macro avg       0.44      0.43      0.41       792
weighted avg       0.69      0.77      0.71       792



In [43]:
#Evaluasi aspek Aroma Pada K=5
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_5)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_5)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_5, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_5, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_5, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_5, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_5, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_5, target_names=['-1', '0', '1']))

Confusion Matrix

[[  8  24   8]
 [  0 614   1]
 [  1 132   4]]

Accuracy: 0.79

Micro Precision: 0.79
Micro Recall: 0.79
Micro F1-score: 0.79

Macro Precision: 0.66
Macro Recall: 0.41
Macro F1-score: 0.42

Weighted Precision: 0.72
Weighted Recall: 0.79
Weighted F1-score: 0.71

Classification Report

              precision    recall  f1-score   support

          -1       0.89      0.20      0.33        40
           0       0.80      1.00      0.89       615
           1       0.31      0.03      0.05       137

    accuracy                           0.79       792
   macro avg       0.66      0.41      0.42       792
weighted avg       0.72      0.79      0.71       792



In [44]:
#Evaluasi aspek Aroma Pada K=7
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_7)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_7)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_7, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_7, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_7, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_7, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_7, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_7, target_names=['-1', '0', '1']))

Confusion Matrix

[[  6  27   7]
 [  0 614   1]
 [  2 132   3]]

Accuracy: 0.79

Micro Precision: 0.79
Micro Recall: 0.79
Micro F1-score: 0.79

Macro Precision: 0.61
Macro Recall: 0.39
Macro F1-score: 0.39

Weighted Precision: 0.70
Weighted Recall: 0.79
Weighted F1-score: 0.71

Classification Report

              precision    recall  f1-score   support

          -1       0.75      0.15      0.25        40
           0       0.79      1.00      0.88       615
           1       0.27      0.02      0.04       137

    accuracy                           0.79       792
   macro avg       0.61      0.39      0.39       792
weighted avg       0.70      0.79      0.71       792



In [45]:
#Evaluasi aspek Aroma Pada K=9
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_9)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_9)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_9, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_9, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_9, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_9, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_9, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_9, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_9, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_9, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_9, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_9, target_names=['-1', '0', '1']))

Confusion Matrix

[[  5  27   8]
 [  0 614   1]
 [  3 133   1]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.51
Macro Recall: 0.38
Macro F1-score: 0.37

Weighted Precision: 0.66
Weighted Recall: 0.78
Weighted F1-score: 0.70

Classification Report

              precision    recall  f1-score   support

          -1       0.62      0.12      0.21        40
           0       0.79      1.00      0.88       615
           1       0.10      0.01      0.01       137

    accuracy                           0.78       792
   macro avg       0.51      0.38      0.37       792
weighted avg       0.66      0.78      0.70       792



In [46]:
#Evaluasi aspek Aroma Pada K=13
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_13)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_13)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_13, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_13, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_13, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_13, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_13, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_13, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_13, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_13, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_13, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_13, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2  33   5]
 [  0 613   2]
 [  1 136   0]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.48
Macro Recall: 0.35
Macro F1-score: 0.32

Weighted Precision: 0.64
Weighted Recall: 0.78
Weighted F1-score: 0.69

Classification Report

              precision    recall  f1-score   support

          -1       0.67      0.05      0.09        40
           0       0.78      1.00      0.88       615
           1       0.00      0.00      0.00       137

    accuracy                           0.78       792
   macro avg       0.48      0.35      0.32       792
weighted avg       0.64      0.78      0.69       792



In [47]:
#Evaluasi aspek Aroma Pada K=20
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_20)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_20)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_20, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_20, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_20, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_20, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_20, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_20, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_20, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_20, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_20, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_20, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2  34   4]
 [  0 613   2]
 [  1 135   1]]

Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.53
Macro Recall: 0.35
Macro F1-score: 0.33

Weighted Precision: 0.67
Weighted Recall: 0.78
Weighted F1-score: 0.69

Classification Report

              precision    recall  f1-score   support

          -1       0.67      0.05      0.09        40
           0       0.78      1.00      0.88       615
           1       0.14      0.01      0.01       137

    accuracy                           0.78       792
   macro avg       0.53      0.35      0.33       792
weighted avg       0.67      0.78      0.69       792



In [48]:
#Evaluasi aspek Aroma Pada K=50
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_aroma_test,predictions_aroma_50)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_aroma_test,predictions_aroma_50)))

print('Micro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_50, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_50, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_50, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_50, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_50, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_aroma_test,predictions_aroma_50, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_aroma_test,predictions_aroma_50, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_aroma_test,predictions_aroma_50, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_aroma_test,predictions_aroma_50, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_aroma_test,predictions_aroma_50, target_names=['-1', '0', '1']))

Confusion Matrix

[[  2  34   4]
 [  0 614   1]
 [  0 123  14]]

Accuracy: 0.80

Micro Precision: 0.80
Micro Recall: 0.80
Micro F1-score: 0.80

Macro Precision: 0.84
Macro Recall: 0.38
Macro F1-score: 0.39

Weighted Precision: 0.80
Weighted Recall: 0.80
Weighted F1-score: 0.72

Classification Report

              precision    recall  f1-score   support

          -1       1.00      0.05      0.10        40
           0       0.80      1.00      0.89       615
           1       0.74      0.10      0.18       137

    accuracy                           0.80       792
   macro avg       0.84      0.38      0.39       792
weighted avg       0.80      0.80      0.72       792

